### ISSUE TITLE
Add missing Titles/Edit wings.json 

### ISSUE THREAD

**Issue by Committee** [llakssz/CIAngel#110]
Aside from manually hex editing the file is there any way to edit/add missing titles from the wings.json file? Example would be Dragon Quest 8, or older Eshop titles.

**Comment by DrakiaXYZ** [comment]
First off, wings.json is a json file, not a binary file.

Second, it's built from the community-contributed 3DS Titlekey Database (Google it if you don't know its domain). If you have titlekeys that don't exist on it, you can contribute them to the site itself, and they will be included in wings.json once they are accepted on the site.

Unless somebody has/contributes the titlekey, there's no way for us to get it, so the game won't be available on CIAngel until someone contributes the key.

**Comment by Committee** [comment]
Got it, will work on trying to contibute.
