### ISSUE TITLE
Feature request: Automatically upload console title keys

### ISSUE THREAD

**Issue by Leseratte10** [llakssz/CIAngel#113]
I've got an idea for a new feature for CIAngel, however I don't know if this is possible: 

At the moment, collecting title keys is done by asking the community to use some other tool to dump the title keys to SD, and then uploading the file to some page on the computer. Someone who just downloads CIAngel because he has heard "cool I can download 3ds games with that" probably doesn't even know such a page exists. 

I think if CIAngel had a feature which automatically extracts all the title keys from the console and upload them to the page every time it also checks for updated title keys, that would help to collect more game keys.

**Comment by noirscape** [comment]
It wouldn't work, AFAIK the current site doesn't have an API to which
encTitleKeys can be send. It simply has a JSON file on it that CIAngel
downloads each time.

Aside from that I'm against this suggestion, mostly because it would
enforce users to participate in sharing copyrighted content.

**Comment by Leseratte10** [comment]
Are title keys "copyrighted content"? It's basically just a number. Can you have copyright on a number?

But this was just a suggestion to make CIAngel find more games, if this is too difficult or you don't like it because of piracy feel free not to implement it.

**Comment by DrakiaXYZ** [comment]
https://en.wikipedia.org/wiki/Illegal_number
