### ISSUE TITLE
code cleanup and building issues

### ISSUE THREAD

**Issue by urherenow** [llakssz/CIAngel#115]
FIrst, there have always been all kinds of bools using u8 in the code. Now, on the current ctrulib and hbkb, this will not even build (although the main page says to use the latest of both):

``build/source/cia.o
In file included from x:/devkitPro/libctru/include/3ds.h:13:0,
                 from source/utils.h:19,
                 from source/lib.h:39,
                 from source/cia.c:19:
source/cia.c: In function 'install_cia':
source/cia.c:49:33: warning: passing argument 1 of 'APT_CheckNew3DS' from incompatible pointer type [-Wincompatible-pointer-types]
  if(R_SUCCEEDED(APT_CheckNew3DS(&n3ds)) && !n3ds)
                                 ^
x:/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
In file included from x:/devkitPro/libctru/include/3ds.h:33:0,
                 from source/utils.h:19,
                 from source/lib.h:39,
                 from source/cia.c:19:
x:/devkitPro/libctru/include/3ds/services/apt.h:446:8: note: expected '_Bool _' but argument is of type 'u8 \* {aka unsigned char *}'
 Result APT_CheckNew3DS(bool_ out);
        ^
build/source/svchax/svchax.o
source/svchax/svchax.c: In function 'do_memchunkhax2':
source/svchax/svchax.c:216:4: warning: implicit declaration of function 'aptOpenSession' [-Wimplicit-function-declaration]
    aptOpenSession();
    ^
source/svchax/svchax.c:217:20: warning: passing argument 1 of 'APT_CheckNew3DS' from incompatible pointer type [-Wincompatible-pointer-types]
    APT_CheckNew3DS(&mch2.isNew3DS);
                    ^
In file included from x:/devkitPro/libctru/include/3ds.h:33:0,
                 from source/svchax/svchax.c:1:
x:/devkitPro/libctru/include/3ds/services/apt.h:446:8: note: expected '_Bool _' but argument is of type 'u8 \* {aka unsigned char *}'
 Result APT_CheckNew3DS(bool_ out);
        ^
source/svchax/svchax.c:220:4: warning: implicit declaration of function 'aptCloseSession' [-Wimplicit-function-declaration]
    aptCloseSession();
    ^
source/svchax/svchax.c: In function 'svchax_init':
source/svchax/svchax.c:473:20: warning: passing argument 1 of 'APT_CheckNew3DS' from incompatible pointer type [-Wincompatible-pointer-types]
    APT_CheckNew3DS(&isNew3DS);
                    ^
In file included from x:/devkitPro/libctru/include/3ds.h:33:0,
                 from source/svchax/svchax.c:1:
x:/devkitPro/libctru/include/3ds/services/apt.h:446:8: note: expected '_Bool _' but argument is of type 'u8 \* {aka unsigned char *}'
 Result APT_CheckNew3DS(bool_ out);
        ^
build/source/utf8proc/utf8proc.o
build/source/config.o
build/source/jsoncpp.o
build/source/main.o
In file included from x:/devkitPro/libctru/include/3ds.h:13:0,
                 from source/main.cpp:25:
source/main.cpp: In function 'Result DownloadTitle(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string)':
source/main.cpp:300:141: error: too many arguments to function 'Result httpcGetResponseStatusCode(httpcContext_, u32_)'
                 if(R_SUCCEEDED(res = httpcBeginRequest(&context)) && R_SUCCEEDED(res = httpcGetResponseStatusCode(&context, &responseCode, 0))) {
                                                                                                                                             ^
x:/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
In file included from x:/devkitPro/libctru/include/3ds.h:45:0,
                 from source/main.cpp:25:
x:/devkitPro/libctru/include/3ds/services/httpc.h:136:8: note: declared here
 Result httpcGetResponseStatusCode(httpcContext _context, u32_ out);
        ^
In file included from source/main.cpp:36:0:
source/fts_fuzzy_match.h: At global scope:
source/fts_fuzzy_match.h:17:17: warning: 'bool fts::fuzzy_match(const char_, const char_)' defined but not used [-Wunused-function]
     static bool fuzzy_match(char const \* pattern, char const \* str)
                 ^
make: **\* [build/source/main.o] Error 1
rm build/source/data/builtin_rootca.bin.c
X:\devkitPro\devkitARM\projects\CIAngel>

**Comment by urherenow** [comment]
yet more ctrulib updates to fix in the code... is CIAngel still being maintained?

**Comment by superbudvar** [comment]
From a release point of view, I don't believe there's any major bug that have been worth patching. That said, it would be nice if it still built and I do see there is a pull request for a fix for the build issue.
I imagine my fellow maintainers are busy with life and other projects right now, but I will try and spend some time this weekend reviewing and bringing things up-to-date

**Comment by DrakiaXYZ** [comment]
Yeah, from my point of view it's at the "Not broke, don't fix it" stage. CIAngel works to download things in its current built state (Using an old ctrulib, "latest" at the time of the last release). 

I haven't had time to look at it in ages, so it hasn't had any maintenance done on the code to get it up to par with the latest changes to the dependent libraries.

**Comment by urherenow** [comment]
well, now it's completely broken because of a website change. It NEEDS to be rebuilt.

**Comment by DrakiaXYZ** [comment]
And fixed
