### ISSUE TITLE
Add an option to upload .cia's

### ISSUE THREAD

**Issue by variantLegend** [llakssz/CIAngel#120]
This isn't really an issue with the program itself, but there are a few missing .cia files that i've seen (such as US region KH3D) and I think there should be an option to upload .cia's yourself.  I dumped my cart of USA KH3D and I would like to add it to the list for people looking to download it.

**Comment by superbudvar** [comment]
I'm afraid you misunderstand how this application works. It has nothing to do with cart dumps and more to do with what you can get from the eShop. Sorry
