### ISSUE TITLE
A lot of GAMES are not available anymore

### ISSUE THREAD

**Issue by Remenabila** [llakssz/CIAngel#122]
Major games like Pokemon versions are not obtainable anymore. Is this normal ?

**Comment by Committee** [comment]
Not really an issue with CIAngel, since this only pulls the files from the CDN based on what is entered in 3ds.titlekeys

**Comment by DrakiaXYZ** [comment]
Make sure you don't have region filtering enabled (Press "R" until it says "Region: Off", not "All"). CIAngel has no control over what is available beyond its local filtering options.

**Comment by Remenabila** [comment]
Yes it was that man, thank you very much. Blessings
