### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by drdeaton** [llakssz/CIAngel#125]
I followed the guide, making sure I  had everything, but I keep getting these errors while building:
`C:/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^~~
In file included from C:/devkitPro/libctru/include/3ds.h:33:0,
                 from source/utils.h:19,
                 from source/lib.h:39,
                 from source/cia.c:19:
C:/devkitPro/libctru/include/3ds/services/apt.h:446:8: note: expected '_Bool *' but argument is of type 'u8 * {aka unsigned char *}'
 Result APT_CheckNew3DS(bool* out);
        ^~~~~~~~~~~~~~~
source/cia.c: In function 'process_tik':
source/cia.c:118:65: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  tik_context.title_version = u8_to_u16(tik_struct.title_version,BIG_ENDIAN);
                                                                 ^~~~~~~~~~
source/cia.c: In function 'process_tmd':
source/cia.c:160:65: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  tmd_context.content_count = u8_to_u16(tmd_struct.content_count,BIG_ENDIAN);
                                                                 ^~~~~~~~~~
source/cia.c:162:65: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  tmd_context.title_version = u8_to_u16(tmd_struct.title_version,BIG_ENDIAN);
                                                                 ^~~~~~~~~~
source/cia.c: In function 'set_cia_header':
source/cia.c:196:70: warning: large integer implicitly truncated to unsigned type [-Woverflow]
   u16 index = u8_to_u16(tmd_context.content_struct[i].content_index, BIG_ENDIAN);
                                                                      ^~~~~~~~~~
source/cia.c: In function 'read_content_size':
source/cia.c:253:47: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  return u8_to_u64(content_struct.content_size,BIG_ENDIAN);
                                               ^~~~~~~~~~
source/cia.c: In function 'get_content_id':
source/cia.c:258:45: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  return u8_to_u32(content_struct.content_id,BIG_ENDIAN);
                                             ^~~~~~~~~~
source/cia.c: In function 'get_title_id':
source/cia.c:263:43: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  return u8_to_u64(content_struct.title_id,BIG_ENDIAN);
                                           ^~~~~~~~~~
source/cia.c: In function 'print_content_chunk_info':
source/cia.c:511:76: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  printf("\n[+] Content ID:    %08lx\n",u8_to_u32(content_struct.content_id,BIG_ENDIAN));
                                                                            ^~~~~~~~~~
source/cia.c:512:74: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  printf("[+] Content Index: %d\n",u8_to_u16(content_struct.content_index,BIG_ENDIAN));
                                                                          ^~~~~~~~~~
source/cia.c:513:73: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  printf("[+] Content Type:  %d\n",u8_to_u16(content_struct.content_type,BIG_ENDIAN));
                                                                         ^~~~~~~~~~
source/cia.c:514:77: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  printf("[+] Content Size:  0x%llx\n",u8_to_u64(content_struct.content_size,BIG_ENDIAN));
                                                                             ^~~~~~~~~~
make: *** [build/source/cia.o] Error 1`

**Comment by DrakiaXYZ** [comment]
Yeah, it's probably not compatible with the latest versions of anything really. Run the version of libctru from around the time of the last commit, that'll probably fix it.

**Comment by drdeaton** [comment]
Yeah, umm... libctru is giving me errors while building...
`c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:104:34: error: unknown type name 'u_int'
 bintime_mul(struct bintime *_bt, u_int _x)
                                  ^~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:145:17: error: unknown type name 'sbintime_t'
 sbintime_getsec(sbintime_t _sbt)
                 ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:151:17: error: unknown type name 'sbintime_t'
 static __inline sbintime_t
                 ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h: In function 'bttosbt':
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:155:12: error: 'sbintime_t' undeclared (first use in this function)
  return (((sbintime_t)_bt.sec << 32) + (_bt.frac >> 32));
            ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:155:12: note: each undeclared identifier is reported only once for each function it appears in
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:155:23: error: expected ')' before '_bt'
  return (((sbintime_t)_bt.sec << 32) + (_bt.frac >> 32));
                       ^~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h: At top level:
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:159:9: error: unknown type name 'sbintime_t'
 sbttobt(sbintime_t _sbt)
         ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:218:9: error: unknown type name 'sbintime_t'
 sbttots(sbintime_t _sbt)
         ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:227:17: error: unknown type name 'sbintime_t'
 static __inline sbintime_t
                 ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h: In function 'tstosbt':
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:231:12: error: 'sbintime_t' undeclared (first use in this function)
  return (((sbintime_t)_ts.tv_sec << 32) +
            ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:231:23: error: expected ')' before '_ts'
  return (((sbintime_t)_ts.tv_sec << 32) +
                       ^~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h: At top level:
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:236:9: error: unknown type name 'sbintime_t'
 sbttotv(sbintime_t _sbt)
         ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:245:17: error: unknown type name 'sbintime_t'
 static __inline sbintime_t
                 ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h: In function 'tvtosbt':
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:249:12: error: 'sbintime_t' undeclared (first use in this function)
  return (((sbintime_t)_tv.tv_sec << 32) +
            ^~~~~~~~~~
c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:249:23: error: expected ')' before '_tv'
  return (((sbintime_t)_tv.tv_sec << 32) +
                       ^~~
In file included from c:\devkitpro\devkitarm\arm-none-eabi\include\sys\time.h:268:0,
                 from c:/Users/(name)/Documents/GitHub/ctrulib/libctru/include/sys/select.h:3,
                 from c:\devkitpro\devkitarm\arm-none-eabi\include\sys\types.h:68,
                 from c:\devkitpro\devkitarm\arm-none-eabi\include\stdio.h:61,
                 from c:/Users/(name)/Documents/GitHub/ctrulib/libctru/source/console.c:1:
c:\devkitpro\devkitarm\arm-none-eabi\include\time.h: At top level:
c:\devkitpro\devkitarm\arm-none-eabi\include\time.h:56:1: error: unknown type name 'clock_t'
 clock_t    _EXFUN(clock,    (void));
 ^~~~~~~
In file included from c:\devkitpro\devkitarm\arm-none-eabi\include\sys\types.h:68:0,
                 from c:\devkitpro\devkitarm\arm-none-eabi\include\stdio.h:61,
                 from c:/Users/Drew/Documents/GitHub/ctrulib/libctru/source/console.c:1:
c:/Users/(name)/Documents/GitHub/ctrulib/libctru/include/sys/select.h:9:23: error: unknown type name 'fd_set'
  int select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout);
                       ^~~~~~
c:/Users/(name)/Documents/GitHub/ctrulib/libctru/include/sys/select.h:9:40: error: unknown type name 'fd_set'
  int select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout);
                                        ^~~~~~
c:/Users/(name)/Documents/GitHub/ctrulib/libctru/include/sys/select.h:9:58: error: unknown type name 'fd_set'
  int select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout);
                                                          ^~~~~~
c:/Users/(name)/Documents/GitHub/ctrulib/libctru/source/console.c:467:2: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  con_write,
  ^~~~~~~~~
c:/Users/(Name)/Documents/GitHub/ctrulib/libctru/source/console.c:467:2: note: (near initialization for 'dotab_stdout.write_r')
c:/Users/(Name)/Documents/GitHub/ctrulib/libctru/source/console.c:485:2: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  debug_write,
  ^~~~~~~~~~~
c:/Users/(Name)/Documents/GitHub/ctrulib/libctru/source/console.c:485:2: note: (near initialization for 'dotab_3dmoo.write_r')
cc1.exe: all warnings being treated as errors
make[1]: *** [console.o] Error 1
make: *** [build] Error 2`

**Comment by urherenow** [comment]
#126

EDIT: now fixed in 0.81
