### ISSUE TITLE
Not downloading or updating wings.json

### ISSUE THREAD

**Issue by EbbFlowe** [llakssz/CIAngel#126]
I just downloaded CIAngel for the first time today via FBI/QR Code. Generally speaking, network features on my 3DS seem to be working, but CIAngel isn't downloading wings.json. I installed an older version of wings.json that I managed to find somewhere, but entering serial numbers from that json doesn't seem to be downloading either, unless I just don't know how to get CIAngel to download things properly.

**Comment by DrakiaXYZ** [comment]
The domain for the titlekey site has expired. We have no control over this, and there are no known mirrors. We just have to sit and wait.

**Comment by nl255** [comment]
The site is back up with the same name only with .gq rather than .com.

**Comment by DrakiaXYZ** [comment]
Hmm, free domain, different host, no HTTPS, and different server configuration. Do we have verification that this is the same person as the original site?

**Comment by TomEke** [comment]
> Yes. titlekeys.gq is run by me again. Here this message is signed with my Bitcoin address

1shAdowJthGC7Sse3pPbdy3bFHZSLe3Wq same as the old one

G6qc31rr1Rf01DjE46jZoFe976sCC0dH3uMP9LOhcdDdErbsn2RA4zfNlIw1ggo394GiGsOV1XIYkdPYEqepxfw=

Free domain as I am still attempting to regain my old one. New host is cheaper. Don't feel like setting up HTTPS yet. Not sure what you mean with configuration, it is still running on nginx.

**Comment by DrakiaXYZ** [comment]
Weird, cause it's returning an Apache page when accessed without a subdomain, that's what I meant by different configuration (Previously it would show a list of the subdomains).

But I know you are who you say, so it's all good to me!

**Comment by BitterAni** [comment]
Im having this issue too. im not very smart, so what do i do to fix this manually? if someone can tell me im sure i could figure out how to do it.

**Comment by DrakiaXYZ** [comment]
Figure out what version of the dependent libraries we used to build CIAngel, get those, set up a development environment, update the source, compile the source, install the CIA.

**Comment by urherenow** [comment]
This was such a pain. I have it built (but not the very latest... software keyboard stuff is all jacked up, so I'm using:
https://sourceforge.net/projects/devkitpro/files/devkitARM/devkitARM_r45/

ctrulib -> git checkout b1f4f43

ciangel-> git checkout b7bd39b

build and add hbkblib

remove the s in https and change com to gq on line 23 of utils.h

done :)

**Comment by noirscape** [comment]
Recommending to add these as submodules to CIAngel to prevent any future
issues. Would you mind creating a PR for this?

**Comment by DrakiaXYZ** [comment]
Fixed in 0.81
