### ISSUE TITLE
When Pressing "Download wings.json" Crashes and Goes to CIA Angel Home Screen

### ISSUE THREAD

**Issue by ElixirDragon** [llakssz/CIAngel#128]
This might not make sense, but when i tried updating the json file, it said "Attempting to download json" for a split second, then crashing. I've tried deleting CIAngel its its folder. I've even tried download a new CIA. It just doesn't work.

**Comment by urherenow** [comment]
should be fixed in 0.81

**Comment by DrakiaXYZ** [comment]
Should be fixed in 0.81, as mentioned
