### ISSUE TITLE
Crashing when trying to search.

### ISSUE THREAD

**Issue by BitterAni** [llakssz/CIAngel#130]
So i open cia, go to any of the search functions, enter something, push enter, Instant crash and closing of ciangel. it doesnt happen slowly, its so fast that its closes within 1/10th of a blink.

**Comment by DrakiaXYZ** [comment]
What version are you running? Also, what string are you entering when you search?

**Comment by BitterAni** [comment]
I'm currently on the latest, But it also happened on the previous one after i installed the JSON from the new website.

here is the link to that situation for more info: https://www.reddit.com/r/3dspiracy/comments/6a63r1/3dstitlekeys_has_moved_to_new_domain/dhdz0c3/

Its not about a specific string, search by name, title id, serial, all of the options crash after entering anything, and pushing search.

I suspect theres an issue with the new website/json that causes it to crash.

**Comment by DrakiaXYZ** [comment]
CIAngel is updated to point at the new titlekey domain, and everything works fine on my O3DS XL during testing. So I don't think it's CIAngel itself, maybe there is a problem with the wings.json file you have. Could you use the download wings.json functionality to make sure you have a correct JSON file?

**Comment by DrakiaXYZ** [comment]
Oh, are you using /json, or /json_enc? Because if you're using /json, that's your problem

**Comment by BitterAni** [comment]
Yesterday i used /json, Also the JSON that was preinstalled on the latest was the issue, i used "download wings.json" and it updated. searching no longer crashes, issue solved.

**Comment by DrakiaXYZ** [comment]
There is no JSON pre-installed, it is only downloaded if the wings.json file is older than a few days and you accept the download.

**Comment by BitterAni** [comment]
I dont know what the issue was then. I deleted the old version before i installed the new one. so there shouldnt have been an old .json it would have used.

Meaning when it installed it should have installed the newest .json when i opened it. unless it didn't which would explain why it crashed if it was trying to search something it didnt have.

Thank you for your help!

**Comment by DrakiaXYZ** [comment]
Deleting the installed title won't delete the /CIAngel/ folder. You most likely just had the old SD files still there that it was reading from.
