### ISSUE TITLE
Games missing 

### ISSUE THREAD

**Issue by brocean13** [llakssz/CIAngel#135]
When looking up a title that was there previously (yesterday) I realized it wasn't there today, when looking up other titles that were there previously present it appears they've all disappeared. 
Ex: Mario kart 7, 3d land, luigis mansion, and shovel knight are all gone and more

**Comment by DrakiaXYZ** [comment]
CIAngel and its developers have no control over what titles are available. Make sure you don't have region filtering enabled ("Off" and not "ALL", as "ALL" is a region).
