### ISSUE TITLE
download CIA to SD

### ISSUE THREAD

**Issue by altlyser** [llakssz/CIAngel#139]
Hello, i need only download cia files to sdcard (and then backup roms to pc). Please add this option.
thanks! 👍

**Comment by urherenow** [comment]
Umm... it's called FunKeyCIA. And it's done ON your PC to begin with.

**Comment by altlyser** [comment]
Ok, thx!

**Comment by llakssz** [comment]
Very late reply, but CIAngel already does this.
You can change the mode via L (maybe R) at the main screen:
* Install game
* Create CIA (put it on the sd card)
* Install/create ticket
(It looks something like that at least) 🌝 

Thanks
