### ISSUE TITLE
Compiled a CIA version

### ISSUE THREAD

**Issue by noirscape** [llakssz/CIAngel#14]
So I managed to compile a cia version of CIAngel :smiley: . It works and has been compiled with commit 9bca282f2bebb033daff446e63525f6784efa32a . Things of note are:
- It has the same issue MangaReader has (not a good icon, it is a black icon and it can only be launched on a regionfree 3DS, so aureinand or rxtools.)
- UniqueID is 0xA617
- For DevMenu, the titlecode is  CTR-H-ANGEL

[ciangel.cia.zip](https://github.com/llakssz/CIAngel/files/228803/ciangel.cia.zip)

Feel free to add this to the current release if you want.

**Comment by llakssz** [comment]
Sure ok, thanks it might be useful for some people.
I won't include your cia in the releases, when the cia creation is automated and the icon is ok... stuff like that, when that is fixed then I will upload with the 3dsx file when I build and upload a new release! :santa: 
Thanks

**Comment by noirscape** [comment]
@llakssz Figured out the issue. The SMDH your makefile creates isn't correct for cia creation. I manually generated an icon.bin using bannertool and using that one seems fix these issues.

I also changed the titleid to CIANGEL. UniqueID remains unchanged.

A working version is attached below, along with the proper SMDH icon.bin, the .elf file I used and the banner file. (if you already installed it, remove the old one, otherwise the icon won't change!). This one doesn't have any issues!

[CIA version.zip](https://github.com/llakssz/CIAngel/files/230016/CIA.version.zip)

The command used to build the cia is (run this inside the directory where you extracted the zip): 

```
makerom -f cia -o ciangel.cia -DAPP_ENCRYPTED=false -rsf cia.rsf -target t -exefslogo -elf CIAngel.elf -icon icon.bin -banner banner.bnr
```

It requires makerom to be installed.

EDIT: Here is the one for commit eae1ea6c44e68da3e2c2b027874e1ce2fa888116 (latest at the time of writing): 

[CIA version.zip](https://github.com/llakssz/CIAngel/files/230034/CIA.version.zip)

**Comment by Ryuzaki-MrL** [comment]
I also made a fully working CIA build, with icon and banner, using a makefile with the 'make cia' rule. Here is my banner: 
![banner](https://cloud.githubusercontent.com/assets/13871621/14726661/67d45dcc-07fa-11e6-9f61-12a12641229f.png)

**Comment by llakssz** [comment]
Thanks guys ok, but ideally this needs to be automated.
I wonder why the smdh file is bad... really? Maybe because of the icon?

And @Ryuzaki-MrL - thanks for the cool banner! but you should take my name off the banner because other users have really helped with this project - it doesn't feel fair.

**Comment by Ryuzaki-MrL** [comment]
Alright, here it is:
![67d45dcc-07fa-11e6-9f61-12a12641229f](https://cloud.githubusercontent.com/assets/13871621/14727914/30ecc5a4-0806-11e6-9062-c1a05e1932a1.png)

**Comment by llakssz** [comment]
Added!
