### ISSUE TITLE
CIAngel stopped creating tickets

### ISSUE THREAD

**Issue by rjalexa** [llakssz/CIAngel#145]
Used CIAngel for a few games and worked great.
Now it downloads wings.json and loads it and shows all titles correctly but when I choose one and press A it says ticket installed and press A and returns to the main menu but already if I read the bottom blue status line I see Queue:0

If I choose Process queue  it says "Queue contains 0 items"

What can I check? The SD card is 32GB and 27 are free.

I can install games from the FREeshop app.

Thank you

**Comment by llakssz** [comment]
Try pressing L or R to change the mode, it sounds like you are in 'install ticket' mode or something?

**Comment by rjalexa** [comment]
Thank you very much. Will have to try in some days when back home with
connectivity.

**Comment by rjalexa** [comment]
You were totally right. So what is the use of the "ticket mode"?

**Comment by llakssz** [comment]
Ticket mode just creates/installs (I forget which one), a ticket.
Using that ticket, you can go to the real eshop and 'redownload' the game, because it believe you are entitled to it due to the presence of the ticket.
