### ISSUE TITLE
wings.json not downloading

### ISSUE THREAD

**Issue by WolfSage55** [llakssz/CIAngel#149]
I have the latest version of Ciangel 0.81 but it wouldn't download the wings.json for some reason can you help please?

**Comment by WolfSage55** [comment]
I've already reinstalled it many times with no success.

**Comment by Committee** [comment]
The URL where the json is downloaded is down, plus with the new security system Nintendo put in effect CDN downloading is now not possible.

**Comment by benoittachet** [comment]
Does that mean CIAngel is now unusable ? Too bad I didn't keep my old wings file...

**Comment by noirscape** [comment]
Yes, CIA downloading is now no longer possible.

**Comment by Unfriended** [comment]
Can someone please shut this project down until we get a solution?

**Comment by noirscape** [comment]
No solution will ever exist and its up to llakssz to archive this repository, nobody else can do it but him.

**Comment by llakssz** [comment]
RIP
