### ISSUE TITLE
Look into straight install from internet

### ISSUE THREAD

**Issue by DrakiaXYZ** [llakssz/CIAngel#16]
I'm looking into this right now, having an "install mode" where instead of creating a CIA, it just downloads directly to an installed state. I've already figured out how FBI does it, and am just working on implementing the functionality.

This will be a different mode compared to normal, probably switched with R or some such, it won't replace downloading and creating a CIA. It's just one less step for people who just want to install something.

**Comment by DrakiaXYZ** [comment]
There we go, seems to work well so far, but still marking it as experimental
https://github.com/llakssz/CIAngel/pull/17

**Comment by llakssz** [comment]
I agree not replacing, this is a great function.
Thank you for your contributions. :factory: 
I wonder if ticket installation is possible with what you have added now, I'll have a look at what AM can do!

**Comment by DrakiaXYZ** [comment]
There's a few ticket related functions, I find the generated docs for ctrulib are outdated, best to look directly at the header: https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/services/am.h

You can also see how FBI does its ticket installation here: https://github.com/Steveice10/FBI/blob/master/source/ui/section/action/installtickets.c

**Comment by llakssz** [comment]
Thanks for the links.
Ok, so this function you added will not help with solely installing a ticket - install_tik - it just puts the data into the the cia that is installing?

**Comment by DrakiaXYZ** [comment]
Yeah, I was actually surprised that just writing the ticket to the CIA handle actually installs it, even if the rest of the CIA install fails the ticket still gets written.

Using the AM Ticket functions shouldn't be too hard though, for installing just tickets.

**Comment by llakssz** [comment]
AM_InstallTicketBegin + AM_InstallTicketFinalize
Doesn't seem too bad! :horse_racing:
Glad you added your name, you deserve it!
