### ISSUE TITLE
Generate a CIA on make

### ISSUE THREAD

**Issue by DrakiaXYZ** [llakssz/CIAngel#18]
Opening a new task for this one, have a few hours before bed tonight, might as well take a look at this.

**Comment by Ryuzaki-MrL** [comment]
I have a makefile ready for this, would it be of any help?

**Comment by DrakiaXYZ** [comment]
Yeah, if you wanna throw it up on Gist and link to it I can take a look, thanks :)

**Comment by Ryuzaki-MrL** [comment]
Done: https://gist.github.com/Ryuzaki-MrL/02fcc24aab70b7c792a418b620899519

**Comment by DrakiaXYZ** [comment]
I've decided to go with using Steveice10's "buildtools" package, as it comes with all the tools for Mac, Windows and OSX as part of it. I also like how he's streamlined things to generate all the required outputs in the proper locations.

Thanks though! :)

**Comment by Ryuzaki-MrL** [comment]
Oh, how could I forget about buildtools? I use it for all my projects :P
The makefile I sent was actually edited from the one I'm using for NotifyMii, which is a mod of the one from buildtools.

**Comment by DrakiaXYZ** [comment]
Opened https://github.com/llakssz/CIAngel/pull/19 for new makefile setup. I used your banner Ryuzaki, hope that's okay :)

**Comment by llakssz** [comment]
Thanks guys. Merged it.

**Comment by Ryuzaki-MrL** [comment]
It's OK. That's why I made the banner.
