### ISSUE TITLE
CIAngel creates invalid tickets that FunKeyCIA doesn't because FunKeyCIA ignores system titles and game updates

### ISSUE THREAD

**Issue by droped** [llakssz/CIAngel#25]
When installing tickets through FBI, the tickets generated with FunKeyCIA never give errors while some of the ones with CIAngel do. It seems so far that all the extra tickets that CIAngel creates have errors because I tried to count the number of ticket install errors and they were as high as 600.

**Comment by droped** [comment]
Linking this as it may be relevant: https://github.com/Steveice10/FBI/issues/72

**Comment by droped** [comment]
I figured it out. FunKeyCIA ignores System titles and game updates. Maybe add an option to skip those too in CIAngel(and don't show them in the search)?

**Comment by llakssz** [comment]
Yes, this will be added.
I'm not sure if DLC is redownloable from the in game dlc stores, if not, I will only allow ignore dlc too.
Although, I believe the tickets are fine.

**Comment by urherenow** [comment]
DLC? Never. That is checked server side every time. Entering the DLC store will, in fact, DELETE all DLC that isn't actually purchased.

**Comment by llakssz** [comment]
@urherenow - but some people don't get it removed. I'm not sure why...
I have been meaning to test.

**Comment by urherenow** [comment]
When entering eshop. 

Entering the in-game DLC shop will ALWAYS remove it.

**Comment by urherenow** [comment]
As long as no DNS uptade blocking is being used, at leas... (Sorry for the double-post. No edit button on my phone)

**Comment by llakssz** [comment]
CFW should add some 'prevent deletion' patch, PS3 cfw has something similar.
Anyway, enough chat! :spaghetti:

**Comment by droped** [comment]
Well, the ticket may actually be fine but they certainly aren't classified as that by FBI... Doesn't matter though as I was only doing a test and I won't be needing every single ticket(don't want to take developers out of business).

**Comment by astronautlevel2** [comment]
I see there's a discussion of when DLC is removed.

It seems from my own tests that when you purchase DLC for a game, the eshop creates a server-side ticket, and if you enter the e-shop with extra DLC it sees your ticket is "corrupt" and overrides it, deleting any DLC installed via CIA.

If you never purchased DLC for a game, entering the E-Shop will NOT remove DLC installed as a CIA for that game.

**Comment by noirscape** [comment]
And what about Howling Theme Tool? Why do those themes get removed, despite the fact that I have never downloaded a theme to my 3DS? Considering themes are pretty much Home Menu DLC (basically), they should be kept too right?

**Comment by astronautlevel2** [comment]
Themes are exactly home menu DLC.

As to why they get removed, I'm unsure. Even downloading a free theme or any bundled theme (ie N3DS Pokemon Edition) seems to cause the ticket overwrite. Basically any official theme installed not as a CIA seems to trigger it.

I plan on doing more research into the rules determining custom themes. My personal devices have remained in line with the behavior I described above though, so it's hard for me to replicate an issue.

**Comment by llakssz** [comment]
If the problem is on the SERVER side and not the local ticket which can be deleted... then yes nothing we can do about that apart from get some cfw dev to patch out the deletion, but that seems like a lot of work

**Comment by llakssz** [comment]
If the problem is on the SERVER side and not the local ticket which can be deleted... then yes nothing we can do about that apart from get some cfw dev to patch out the deletion, but that seems like a lot of work
