### ISSUE TITLE
Rewrite UI

### ISSUE THREAD

**Issue by DrakiaXYZ** [llakssz/CIAngel#26]
Some comments on the forum got me thinking, it may be possible to utilize a menu type system similar to Luma3DS's config menu instead of the (quickly dwindling) collection of keys we are using right now.

Ideas on this would be initialize the console on the bottom screen instead of the top, only show the keyboard when we actually need to get user input (I can't really think of a point at which we'd need both console output and the keyboard showing, if we can write positioned text on the top screen), and clear the bottom screen of the keyboard/switch back to console mode when we are doing something such as installing.

Might be quite a bit of code change, but it would result in a far cleaner and easier to use UI. It would also allow us to implement a config menu for changing some things like whether to export system or DLC tickets, for example.

I'm back home now, so will take a look at this over the next day or so. This sound like something you'd accept as a PR llakssz?

**Comment by llakssz** [comment]
I was planning to add a state machines to this, would this be better before or after a ui 'overhaul'?
What about using moving the existing functional code to base homebrew that already has nice lists (for displaying games + their icons) and gui, like homebrew menu?
I'd be happy to accept it sure, I'd be happy to work on it too.

**Comment by DrakiaXYZ** [comment]
Might be better after, since it would probably require pretty tight integration with the UI code.

One problem with trying to add icons (And even just a full list) would be memory limitations and speed. If you add icons, they'd need to be grabbed from somewhere, which could be slow for the current encTitleKeys.bin file (With its 1000+ titles). For a full list of installable titles, you'd need to make sure the list can handle 1000+ entries without completely killing performance/memory.

I was actually looking at FBI's menu code, which I find to be a masterpiece of coding, but that may be a little too complicated (It uses a lot of function pointers for callbacks, threads, etc). We could technically write our own "large list" handling code using the same type of setup that Luma3DS uses, but we'd have to deal with scrolling beyond the main screen ourselves I think.

**Comment by llakssz** [comment]
If there will be a list, I think it would be ok to have the top 6 (or X) search results appear in the list, that shouldn't kill memory too much. X is small enough that we don't need to scroll.
Using the bottom screen is sensible
Loading images from local data for 6, even 20 titles shouldn't be too bad.
We would never have all 1000+ items in the display list at one time.
They seem happy enough in memory as objects though, that is good. :art:

https://www.3dbrew.org/wiki/SMDH#Icon_graphics for the future, I wonder how we can display this data.

**Comment by Paradox355** [comment]
> Ideas on this would be initialize the console on the bottom screen instead of the top, only show the keyboard when we actually need to get user input 

I was thinking about this as well, and was planning to implement that after testing my code for using button presses instead of the keyboard for making selection from search results. Unfortunately I haven't been able to to test that because I've been unable to do a build. I'm thinking it's due to problems with win32 make in git bash but I'm not really sure what's causing it to fail.

**Comment by DrakiaXYZ** [comment]
https://github.com/llakssz/CIAngel/pull/35

Opened a PR for menu based system

**Comment by llakssz** [comment]
Wonderful! :zap:
