### ISSUE TITLE
When typing to search for a name, the keyboard animation freezes

### ISSUE THREAD

**Issue by ghost** [llakssz/CIAngel#27]
I found a bug. When typing in the text to search for a name, the keyboard animation freezes. This makes it hard to see the special characters menu and to see if you capitalized the letters.

**Comment by llakssz** [comment]
This is a bug with the keyboard or specifically CIAngel?
I'm not sure, maybe we should talk here? http://gbatemp.net/threads/hbkblib-a-3ds-keyboard-library.397568/

**Comment by ghost** [comment]
Not sure. I just think it has some incompatibility with 0.45. It worked earlier with 0.4. Didn't you edit parts of the keyboard to add compatibility?

**Comment by DrakiaXYZ** [comment]
This is fixed in https://github.com/llakssz/CIAngel/pull/35
We were missing a call to swapping the buffers when typing.
