### ISSUE TITLE
Increment version number when building CIA so we can install over existing app

### ISSUE THREAD

**Issue by llakssz** [llakssz/CIAngel#29]
Save the current version (no real relation to the CIAngel release version is needed)
Increment it by 1 each time. Pass in the version when creating cia.
The max version is FFFF. If we ever get there, simply delete the installed app and go back to 1 and start again.

**Comment by llakssz** [comment]
I'm not so sure if this is necessary, because the cia did install fine over the existing installation.
But before, it wasn't, maybe because I tried mistakenly installing the exact same created cia.
I might close this.

**Comment by Ryuzaki-MrL** [comment]
This isn't needed. All title managers will install a CIA over an existing title if that CIA's version is **equal or greather than** the installed title's version.

**Comment by llakssz** [comment]
equal... i didn't know that! ok :) thanks
