### ISSUE TITLE
Searching for certain games shows no or unrelated results, even though the game exists in the database

### ISSUE THREAD

**Issue by Masamune3210** [llakssz/CIAngel#30]
Certain games will never appear in the search results no matter what is tried

Have tested with Etrian Odyssey Untold, which only brought Etrian Mystery Dungeon, and Azure Striker Gunvolt which brought up nothing related

**Comment by llakssz** [comment]
I know the search is not perfect, but don't say "not matter what is tried" - I searched for 'etrian odyssey untolfd the millenium girl' and it came up! (my search contained those 2 spelling mistakes, my fault, but it worked)
The longer the game's name, the harder it will find, the more you will have to type.
The search is not predictive, it just tries to fix typing mistakes, which let us account for unenterable characters in names, things like TM, accented characters, etc.

This is planned to be improved in the future.

**Comment by Masamune3210** [comment]
Sorry, the wording could probably have been better. I was unaware that the searching was mostly for spelling at the moment. My apologies

**Comment by llakssz** [comment]
No problems, thanks for the help :)

**Comment by timX24968B** [comment]
I tried everything from above, and literally NOTHING came up.

**Comment by llakssz** [comment]
it sounds like you don't have the wings.json file.
