### ISSUE TITLE
(Suggestion) Re-Add input.txt support and delete folders from CIAngel folder when done installing.

### ISSUE THREAD

**Issue by ghost** [llakssz/CIAngel#32]
Would you be able to re-add the input.txt support and also, when using the auto-install feature, could you have CIAngel delete the extra tmp folders and files please?

**Comment by Paradox355** [comment]
From latest commit comments:

> ticket generation will return later.

Also, there has been no release since that feature was removed. So unless you're compiling your own build from latest commits, you should be fine.

**Comment by llakssz** [comment]
yes tmp folder deleting should be added.
I think you are in the minority, you really want the ability to make a text file on the computer, then download that 1 title?

**Comment by ghost** [comment]
Sorry, just currently, CIAngel doesn't support all CIA finding. I guess this could also be solved if the wings.json file is updated. I'm sorry if it sounded like I'm being a little nit-picky and offending, my apologies! I just love the app!

**Comment by ghost** [comment]
I wasn't able to find "3D Streets of Rage 2" but I was able to download it using the input.txt file with the Title ID and Encrypted Title Key here: LINK REMOVED . I wasn't able to understand how to " give it a title id and the encrypted key " option. How do I do that option?

**Comment by llakssz** [comment]
you press X (I think) - you are able to type the title id and key.

**Comment by DrakiaXYZ** [comment]
This PR brings back input.txt support: https://github.com/llakssz/CIAngel/pull/35

As for temp files, when using install mode, the only files that get created are /CIAngel/tmp/tmd and /CIAngel/tmp/cetk. They are overwritten for every successive install you do, so I'm not really sure deleting them is all that important.
