### ISSUE TITLE
Add ticket installation

### ISSUE THREAD

**Issue by llakssz** [llakssz/CIAngel#38]
Instead of the bool to check whether to install directly or make a cia, have a value that has a 3rd option of installing just the ticket.
This could be limited just to titles of the same region as the device, and could be made not available for DLC because from what I hear, that is not available to be redownloaded.

**Comment by llakssz** [comment]
@Kyraminol -- I just added this, thanks :)
I had a problem, for me there was no AM_InstallTicketFinish, only Finalize... I'm not sure who is using the old ctrulib, but I thought I was using the latest one, maybe yours is old? :mount_fuji:

**Comment by cerea1killer** [comment]
It seems AM_InstallTicketFinish is correct per https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/services/am.h

**Comment by Kyraminol** [comment]
Sorry didn't notice github notification :laughing: i rebuilt ctrulib the day I started TIKdevil, it was the lastest :D

**Comment by llakssz** [comment]
Yep I'm in the wrong, sorry! It's changed to finish now.
