### ISSUE TITLE
Please provide the .cia directly from the release page

### ISSUE THREAD

**Issue by ksanislo** [llakssz/CIAngel#40]
@llakssz Could you please post the latest .cia file directly under the 0.50 release? Also, would you then be willing to generate a QR code with that file link and post that image on the release page as well? That would allow users of the latest [FBI](https://github.com/Steveice10/FBI) (redirect patch merged, next release will play nicely with github) or [QRWebLoader](https://github.com/ksanislo/QRWebLoader) to install directly from github without downloading the file separately.

**Comment by llakssz** [comment]
You really want a separate entry on the release for the CIA? I used to do it but didn't think it was that important now.
I saw FBI doesn't have a separate CIA link.
If github could provide be a static link to the latest CIA each release I may add a download function in the application itself - possibly. But I don't think it does, so I would have to host it somewhere else.
But I don't think I'm going to be generating a QR code each time.

**Comment by ksanislo** [comment]
At least with an uncompressed .cia link, it can be copied/pasted or you can use a browser based QR plugin to make links to quick install.

FBI lacks a separate .cia link at the moment as well since the whole URL driven web-install is a fairly new feature (2.1.1 can't follow github's url redirection, 2.1.2 will be patched for that, but likely still can't self-upgrade directly.) I would assume that once it makes sense for it to be able to directly download a .cia for itself, that will change.

I know it takes an additional 30 seconds or so to copy/paste a URL back into a QR generator and then copy the image back, but it's definitely worth a bit of extra hassle for end users. Being able to QR install apps to the 3DS makes upgrading or installing new homebrew to the 3DS extremely simple for everybody, there's no need for using a ftpd or pull the SD card anymore.

On a semi-related note, if you wanted to integrate your own self-upgrade-as-a-.cia functionality, you could fairly easily parse out your own latest release from the API, and do something like [AutoLoader](https://github.com/ksanislo/AutoLoader) to install the latest version.

**Comment by Paradox355** [comment]
@llakssz Have you checked out GitHub Pages? You can set up a custom web page for projects. It's how dukesrg hosted the .bin payloads accessible via the web.

**Comment by DrakiaXYZ** [comment]
The main problem is even a GitHub page is another thing we have to keep tabs on/keep updated. I do agree that having just the CIA as a standalone option on the Releases page may be useful though (Since most people will want just the CIA).

**Comment by llakssz** [comment]
Ok, I'll start uploading just the CIA and separate 3dsx again, not all in 1 zip file.
I'll see if I can do something to have a constant link.
I mean, this program is just a little over a week old but has made loads of progress. Eventually releases will slow down, things will be calmer.

**Comment by ksanislo** [comment]
@llakssz Here's some data regarding QR code use that I collected via the [.cia build of lumaupdate on reddit yesterday](https://www.reddit.com/r/3dshacks/comments/4gocaz/luma3ds_updater_112_formerly_arn_updater_released/d2jekzg), both as a direct link and as a QR link.

94 downloads have occurred via the QR code
78 have been browser based downloads of the .cia file
14 IP addresses downloaded both ways (meaning they saved the cia from the browser, but then installed via the QR anyway.)

So, on a preliminary test, it certainly looks like providing a QR code would be worth the extra effort.

**Comment by llakssz** [comment]
@ksanislo - but that is when given a choice. I think most people would not boycott/be too lazy to download an application simply because there is no QR code.
As I said, I will look into it, especially as releases slow down!

**Comment by ksanislo** [comment]
@llakssz You're right, I doubt people would boycott anything over the lack of it, but it definitely makes installing/upgrading much faster and easier. Particularly for the people who use CIAngel for the express purpose of not needing or having easy access to a computer. Thanks for giving the idea consideration!

**Comment by ghost** [comment]
I make a CIA QR from https://webqr.com/create.html on my phone

**Comment by DrakiaXYZ** [comment]
I've created a PHP script that creates a QR code pointing at the latest releases CIAngel.cia file, and opened a PR to add this image to the README: https://github.com/llakssz/CIAngel/pull/59
