### ISSUE TITLE
Black screen when returning from sleep mode

### ISSUE THREAD

**Issue by spud29** [llakssz/CIAngel#42]
When I have CIAngel running and close my N3DS XL and then reopen it, it gives me a black screen that doesn't respond to input as far as I can tell and I have to force shutdown my system.

**Comment by Paradox355** [comment]
I saw this today as well, but it not the current build. Not sure if current build exhibits this behavior.

**Comment by spud29** [comment]
Yes I have the latest version. It's had this bug since the previous version

**Comment by llakssz** [comment]
I don't think any homebrew plays well with sleep mode... if you can give an examples of homebrew that do work fine, I'll take a look and see what they are doing! :)

**Comment by spud29** [comment]
JK Save Manager, CTRX SD Explorer, and FBI all work fine returning from sleep mode, they are all CIA versions, CIAngel is as well.

**Comment by DrakiaXYZ** [comment]
Hmm, seeing the same behaviour in the .3dsx version. Does anyone know what version this started in?

**Comment by spud29** [comment]
Just tested every version, it's only been happening since 0.5, maybe something related to the menu UI?

**Comment by DrakiaXYZ** [comment]
This is fixed with my queue pull request
