### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by fabinhojcr** [llakssz/CIAngel#54]
When searching for the mickey ciangel 0.7 gives error and Restarts 3ds.

**Comment by superbudvar** [comment]
what are you searching for? "the mickey" or "mickey"

**Comment by superbudvar** [comment]
this maybe the single result crash I've just pushed a fix for

**Comment by fabinhojcr** [comment]
I write only mickey and this happens.

**Comment by fabinhojcr** [comment]
It was only with this word this happened, I wrote other and worked properly.

**Comment by cerea1killer** [comment]
Did you have a region filter enabled? That would return one result, and this would fall in with #55 and #56

**Comment by fabinhojcr** [comment]
I do not I enabled no filter region and only with the word "Mickey" that this happens, does not even appear the result, ciangel closes and 3ds restarts.

**Comment by DrakiaXYZ** [comment]
Mickey only returns a single result on my system, so this would have been caused by #56, it's fixed with the new merge
