### ISSUE TITLE
Home menu close crash v0.7

### ISSUE THREAD

**Issue by Xenosaiga** [llakssz/CIAngel#55]
If CIAngel is in the background and you try to close it from home menu it sticks on the "Closing Suspended Software" screen and requires a Hard Power Off to fix.

**Comment by superbudvar** [comment]
I've noticed this. I think it maybe that we are't hooking into the close call, meaning we just ignore the home menu indefinitely (or crash)

The fix maybe to remove aptMainLoop() so the home button doesn't work (until we have a proper fix at least)

**Comment by DrakiaXYZ** [comment]
Hmm, aptMainLoop is what should be returning false on exit, which I thought I had cascade all the way down to main. Might have missed something though

**Comment by superbudvar** [comment]
@TheDgtl I can't say for certain, but I had worked out you _can't_ use home if your loop doesn't call it. I also spotted a hook called APTHOOK_ONEXIT[https://smealum.github.io/ctrulib/apt_8h.html#a65688ade2995260aadd4ab7539df58a6a0dad384082914a54947b2407dc5edf75](in this doc)

But I'm completely guessing, there's a distinct lack of info on this kind of thing, unless I'm not looking in the right places

**Comment by DrakiaXYZ** [comment]
Yeah, a lot of what I've been doing is guess work and trial and error :)

I'll take a look at this tonight, and see if I can sort out what might be going on.

**Comment by DrakiaXYZ** [comment]
Got a fix in the works for this

**Comment by DrakiaXYZ** [comment]
https://github.com/llakssz/CIAngel/pull/58
