### ISSUE TITLE
Test SSB

### ISSUE THREAD

**Issue by DrakiaXYZ** [llakssz/CIAngel#62]
Have had a couple users complain this particular title is failing to install, I thought I'd already tested it, but going to re-download it just to verify.

**Comment by llakssz** [comment]
It could be the key, or just being a popular game, many people had installed a bad version of the cia before. But nice to reassure some users!

**Comment by DrakiaXYZ** [comment]
Gave it another download (After deleting the ticket in FBI), and it still installs fine. I'm going to assume people just have bad tickets from previous installs.
