### ISSUE TITLE
Save settings somewhere.

### ISSUE THREAD

**Issue by noirscape** [llakssz/CIAngel#63]
At the moment, region and install options aren't saved upon exiting. This is sorta annoying, because I have to set the region each time to EUR, and change install mode to CIA. Saving these settings in a file would get around this issue.

**Comment by DrakiaXYZ** [comment]
Actual config is something I really do want to add, hopefully I'll have some time to get something thrown together soon.

**Comment by DrakiaXYZ** [comment]
#88
