### ISSUE TITLE
Stream ticket data instead of writing to ticket folder, then deleting.

### ISSUE THREAD

**Issue by llakssz** [llakssz/CIAngel#67]
It can confuse some users as to why there is a 'ticket' folder in the CIAngel folder, because the tickets are not dumped anymore, they are installed directly.
So, good to stream and send the data when it is needed instead of building a file, reading it, then deleting it.
Or at the very least, write the ticket to the tmp folder.

Maybe if we can hook the exit call, delete the tmp folder when the app exits?

**Comment by DrakiaXYZ** [comment]
#84 Not the best solution (Still doesn't stream right to the install function) but it does leave a nice empty folder after installation is done :)
