### ISSUE TITLE
Will fail to download json if 'CIAngel' folder doesn't exist on SDCard

### ISSUE THREAD

**Issue by usagirei** [llakssz/CIAngel#68]
Possibly, needs double checking on other console units as well.

**Comment by cerea1killer** [comment]
This is fixed in version 0.75, please update and try again

**Comment by usagirei** [comment]
I mean, I literally downloaded it five minutes before posting that message.
Unless the QR Code in the readme was wrong, then i should have had 0.75 installed

EDIT: Which is the case.
QR Code in the README points to 0.72
So yeah, this should be a non issue, aside from the readme link

**Comment by DrakiaXYZ** [comment]
The hell, Github is caching the image, stupid Github.

https://thedgtl.net/3ds/CIAngel.php  <-- The PHP file there will always have the latest QR code, it's what GitHub was supposed to be showing.

**Comment by usagirei** [comment]
Might want to add a few Cache-Related HTTP Headers on the php script to see if it stops caching, like "Cache-Control:no-cache" and so on

**Comment by DrakiaXYZ** [comment]
Yeah, I've updated the cache headers now, but it won't take effect until the image is re-cached by Github on their CDN.
