### ISSUE TITLE
keys site is moving

### ISSUE THREAD

**Issue by superbudvar** [llakssz/CIAngel#73]
and to https.

We will need to update to reflect this, but there is now also a https redirect, which breaks the download

**Comment by DrakiaXYZ** [comment]
Just saw that, if you're not planning on looking at it I'll see if I can fix it after work.

**Comment by superbudvar** [comment]
I've had a quick look to see if I can work out SSL requests, but I'm waiting til after work too :grimacing:

**Comment by superbudvar** [comment]
That starts about now, so I think that probably gives me about 5 hours do get a fix, or it's over to you :stuck_out_tongue_winking_eye:

**Comment by DrakiaXYZ** [comment]
Lol, yup, I'm at work for another 6.5 hours, so you've got some time ;)

**Comment by superbudvar** [comment]
well...fail...

It seems there's an ssl.c in 3ds-examples which I've been trying to add to the project, but it doesn't just use an url but a hostname and a path, so I got lost attempting to split strings. I'll commit what I've got, but tbh, it may be the long way round; it may be possible to do it all using httpc alone.

It seems we also need a root cert generating too. Again, the example comes with one that I was using temporarily

**Comment by llakssz** [comment]
how about the project I originally forked from, does that help you?
https://github.com/machinamentum/FirmwareDownloader/blob/master/source/main.cpp#L264

**Comment by cerea1killer** [comment]
I have some stuff, including separating all net stuff into a net.h/c, I can
commit that in the morning. It's based on a mix of firmware downloader, and
SSL from the example.

**Comment by DrakiaXYZ** [comment]
Does it actually work the that sites new Let's Encrypt SSL cert? Cause my 3ds totally chokes on Let's Encrypt certs, even with the normal browser :/

**Comment by cerea1killer** [comment]
Haven't gotten it functional yet, but that should just be a matter of
making sure the root chain for the SSL cert context includes let's encrypt
in the chain

**Comment by DrakiaXYZ** [comment]
Boom
https://github.com/llakssz/CIAngel/pull/74

**Comment by DrakiaXYZ** [comment]
Also, just for informational purposes, while the index for the nfshost version of the site is down, the json is still up, so people using CIAngel right now still have access to wings.json :+1:
