### ISSUE TITLE
Should we overwrite tickets?

### ISSUE THREAD

**Issue by DrakiaXYZ** [llakssz/CIAngel#75]
I've seen quite a few users who have installed a CIA with a bad ticket ages ago, then tried to use CIAngel to install a CIA only to have it fail at 99% because of the bad ticket. 

One way around this would be during install mode, delete the existing ticket before we install the new one. I can't see it causing much of an issue, any objections?

**Comment by superbudvar** [comment]
makes sense, and will reduce users claiming there's a bug

**Comment by llakssz** [comment]
It is possible to have multiple tickets for 1 title, so does deleting the ticket delete all of the tickets, or we have to do it 5 times to be relatively safe that we got them all?
But yes, very good idea.

**Comment by DrakiaXYZ** [comment]
As far as I know a title only has one ticket, when you remove a ticket with FBI it's completely gone, so we'd probably use the same function they do.

**Comment by llakssz** [comment]
One title can have multiple tickets, for example you get a ticket for dlc when you go to a game's dlc store (although that ticket doesn't entitle you to any dlc it has the key) - if you buy some of the dlc you will get another ticket which says what dlc you are entitled to, if you buy some more of dlc, you get another ticket etc.

I'm not sure why but for some titles I have seen 3 or 5 tickets in my ticket.db, for things that were not even dlc. Although, maybe just because the data was in the .db, it doesn't mean that the 3ds was able to read it, maybe those tickets were signaled for overwrite when possible... I'm not sure.

**Comment by DrakiaXYZ** [comment]
Hmm, I assumed this part of the ticket generation was what gave access to different parts of DLC: https://github.com/llakssz/CIAngel/blob/master/source/cia.c#L187

Because we use a single ticket for installing, say, all the Smash DLC, we don't need a ticket per piece of DLC. I figured what was happening (And it would explain why DLC gets overwritten with "none" when visiting the in-game DLC shop) is that the ticket was actually being updated with the new DLC you buy (In the case of not owning any, overwritten with none).

I don't know enough about the ticket DB to confirm that though. But so far the answer to every "It gets stuck at 99%" is "Delete your ticket in FBI"

**Comment by llakssz** [comment]
The ticket has flags that I set to 'everything unlocked'. The cia header is not the same as the ticket right?
Anyway, every content the TMD lists, make_cdn_cia needs it present to build the CIA.
So, if I have a ticket that gives access to 300 themes, I need to build a CIA with 300 themes, actually, no, the CIA would have to be built with all the contents the TMD says, so probably 1000 or something!

With edits to the CIA creation, I'm sure we could choose what contents to include and what contents to ignore. (So we can create selective dlc cias, not important though) Maybe that is the line of code you linked to.

Maybe we are misunderstanding each other a little, I was just suggesting it's possible to have more than 1 ticket for something = it's possible to have more than 1 bad ticket.
But I assume the 3ds can only have 1 ticket at a time... something like that. The old ones maybe are ignored etc.

I don't think we have to worry about deleting more than one time to remove any multiple tickets, I think the 3ds will take care of that itself.

**Comment by DrakiaXYZ** [comment]
Ah, you're right, I missed a part of the code.

Anyways, yeah, I don't believe it would be required to delete the ticket multiple times, my guess is the multiple tickets you see in the DB are just ones marked for deletion, and only one is "active" at a time. Atleast I've never managed to get FBI to still show a ticket after deleting it (Until I install a new ticket).
