### ISSUE TITLE
Picross E6 Doesn't Download Right

### ISSUE THREAD

**Issue by Mattshark** [llakssz/CIAngel#78]
Downloaded as CIA, Installed Directly, etc. multiple times to confirm; always endlessly loops the Nintendo 3ds Logo upon run, rendering it unplayable. The other Picross games work fine, just E6 messes up.

**Comment by llakssz** [comment]
As you can probably imagine, it's not something specific to this game, just that it probably needs an extra decryption key, the 'seed'.

Simply go to the game's page in the eshop, this will give you the seed and the game will now play fine.

If you can't access eshop, or the game is not in your region and so it won't be in your eshop, then you will have to do something else. 

Add the seed manually or with some other tool, etc.

I'm closing this issue but you can still comment  for when you get it fixed.

**Comment by Mattshark** [comment]
Ah, okay. That makes sense.

Could you add this to the thread as a clarification to others having
trouble with this? I sure didn't think about it until just now
