### ISSUE TITLE
Don't show titles that lack an encrypted titlekey

### ISSUE THREAD

**Issue by DrakiaXYZ** [llakssz/CIAngel#81]
Looks like sometimes the titlekey database lacks an encrypted titlekey (Since only decrypted can be submitted, and the admin encrypts them manually, I'm guessing). We should probably filter those out.

**Comment by TomEke** [comment]
Why not use /json_enc like Shameless uses?

**Comment by DrakiaXYZ** [comment]
Oh right, I forgot he had that JSON access point, thanks! :+1:

**Comment by DrakiaXYZ** [comment]
Doesn't look like json_enc is actually working like I thought it would :( I'm seeing Zombie Panic in Wonderland DX in there, which has a null encTitleKey. The main difference seems to be a small size saving in that it doesn't have decTitleKeys in it

**Comment by DrakiaXYZ** [comment]
#85

**Comment by TomEke** [comment]
> Doesn't look like json_enc is actually working like I thought it would :( I'm seeing Zombie Panic in Wonderland DX in there, which has a null encTitleKey. 

Oops. Fixed that.
