### ISSUE TITLE
Add encTitleKey.bin

### ISSUE THREAD

**Issue by alice157** [llakssz/CIAngel#9]
This seems like the best place to keep track of what we're working on, but if it isn't, let me know.

I've started work on parsing an encTitleKey.bin and letting the user choose a key/id pair. I won't be able to work too much on it today besides what I've already done (currently drowning in homework) but it should be ready very soon.

**Comment by llakssz** [comment]
I've nearly finished it myself, anyway we talked about it on the forums.
I added fetching the latest file from 3ds.nfshost.com too.

**Comment by llakssz** [comment]
I added some code to the experimental branch.
We just need to read the data and convert it to a string :)
Apart from that, it's nearly finished! :ok:

**Comment by llakssz** [comment]
:egg: Added!
