### ISSUE TITLE
Add "list/show all titles" option

### ISSUE THREAD

**Issue by nope-dot-jpg** [llakssz/CIAngel#93]
Since we cannot search for Japanese games by their name (Ciangel has no foreign keyboard) , and many jp games/apps don't have a space in their names, such option is needed and would be good in general, like if we have no idea on what to download.

examples:
ニコニコ
クラブニンテンドーピクロス
いつの間にテレビ
いつの間に交換日記
カルドセプト®
ニンテンドービデオ
美人時計
スーパーマリオブラザーズ
etc...

**Comment by DrakiaXYZ** [comment]
I've added the ability to search by game serial, this is about as close as I think we'll get to a "show all" option, and is more useful from my perspective.
