### ISSUE TITLE
Original Rytmik missing from Wings.json

### ISSUE THREAD

**Issue by Mattshark** [llakssz/CIAngel#97]
Can't find the Title Key anywhere online either... only Rytmik Retrobits and Rock Edition, never the original for some reason

**Comment by cerea1killer** [comment]
That means that no one has purchased the game and uploaded the title
keys/ticket online. Although, it looks like the original Rytmik may have
been pulled from the store.

The database is at https://3ds.titlekeys.com/ if you want to look on there.

**Comment by DrakiaXYZ** [comment]
We have no control over what games are included in the database we use, they are all community contributed titlekeys.
